### ISSUE TITLE
Pro Firebase!!

### ISSUE THREAD

**Issue by josephting** [jerry54604/Artket#1]
Sasuga pro Jerry keep play pro thing :open_mouth:

**Comment by jerry54604** [comment]
LOL!!! firebase pro me no pro 😞

**Comment by josephting** [comment]
Firebase pro, people who use firebase also pro. :+1:

**Comment by jerry54604** [comment]
me just noobing around 😶

**Comment by josephting** [comment]
noobing around also so pro :disappointed: 
No modify meh? Just generate using program? :rofl:

**Comment by jerry54604** [comment]
lol
angular project generate using cli self added firebase
havent got time to work on it yet 😮
